### ISSUE TITLE
Strings are quoted when containing double colon

### ISSUE THREAD

**Issue by dvic** [optimumBA/github_workflows_generator#4]
https://github.com/optimumBA/github_workflows_generator/blob/eb9a454f68eb3cfadb1f9ad675cb4e6ed71bca24/lib/github_workflows_generator/yml_encoder.ex#L45

What's the reasoning here? Because this is perfectly valid YAML I believe?

```yaml
---
example: |
  this: is valid
```
